CREATE TABLE CITIES(
    CITY_ID INT, 
    [CITY] CHAR(20),
    [STATE] CHAR(20),
    PRIMARY KEY (CITY_ID)
);

CREATE TABLE WAREHOUSES(
    CITY_ID INT,
    WID INT,
    WNAME CHAR(30),
    [LOCATION] CHAR(20),
    [EXTRA CONTEXT] JSON,
    FOREIGN KEY (CITY_ID) REFERENCES CITIES(CITY_ID)
);

CREATE TABLE STORES(
    WID INT,
    [SID] INT,
    [STORE_NAME] CHAR(20),
    [LOCATION_CITY] CHAR(20),
    FOREIGN KEY (WID) REFERENCES WAREHOUSES(WID)
);

CREATE TABLE CUSTOMER(
    CNO INTEGER,
    CNAME CHAR(50),
    ADDR VARCHAR(50),
    CU_CITY CHAR(20)
);

CREATE TABLE ORDERS(
    CNO INT,
    ONO INT,
    ODATE DATE,
    FOREIGN KEY (CNO) REFERENCES CUSTOMER(CNO)
);

CREATE TABLE ITEMS(
    [SID] INT,
    ONO INT,
    ITEMNO INT,
    [DESCRIPTION] TEXT,
    [WEIGHT] DECIMAL(5,2),
    [COST] DECIMAL(5,2),
    FOREIGN KEY (ONO) REFERENCES ORDERS(ONO),
    FOREIGN KEY ([SID]) REFERENCES STORES([SID])
);